@startuml
title Datenatlas – CAV:1131
class CAV_1131 {
  Name: Codeliste, Code
  Prozesse:
    - Bestellung einer technischen Konfiguration (MSB)
    - Sperrung und Entsperrung eines Anschlusses
}
class CAV_1131_msg_1 {
  Nachricht: QUOTES 1.3a
  Kontext: Beispiel:
  Pflichtfeld: Nein
  Codes: 000, 10, 17, 200, 35, 999, AHZ, BGZ, CAV, DKZ, EDI, EHZ, IVA, LAZ, MAZ, MME, MRG, OCR, TRZ, UGZ, WGZ, WSZ, Z01, Z02, Z03, Z04, Z05
  Prozesse: Bestellung einer technischen Konfiguration (MSB), Sperrung und Entsperrung eines Anschlusses
  Quelle: QUOTES_MIG_1_3a_Fehlerkorrektur_20241213.pdf
}
CAV_1131 --> CAV_1131_msg_1 : verwendet in
class CAV_1131_proc_1 <<process>> {
  Bestellung einer technischen Konfiguration (MSB)
  Gesetze: MsbG, EnWG
  Zusammenfassung: Erläutere den Prozess zur Bestellung einer spezifischen technischen Konfiguration bei einem Messstellenbetreiber, beispielsweise für ein intelligentes Messsystem.
}
CAV_1131 ..> CAV_1131_proc_1 : eingebettet in
class CAV_1131_proc_2 <<process>> {
  Sperrung und Entsperrung eines Anschlusses
  Gesetze: StromGVV
  Zusammenfassung: Beschreibe den End-to-End-Prozess für die Sperrung und Wiederherstellung eines Netzanschlusses.
}
CAV_1131 ..> CAV_1131_proc_2 : eingebettet in
@enduml