@startuml
title Datenatlas – CCI:7036
class CCI_7036 {
  Name: Merkmal
  Prozesse:
    - Bestellung einer technischen Konfiguration (MSB)
    - Sperrung und Entsperrung eines Anschlusses
}
class CCI_7036_msg_1 {
  Nachricht: QUOTES 1.3a
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: 10, 13, 17, 35, 999, CCI, OCR, Z60
  Prozesse: Bestellung einer technischen Konfiguration (MSB), Sperrung und Entsperrung eines Anschlusses
  Quelle: QUOTES_MIG_1_3a_20240619.pdf
}
CCI_7036 --> CCI_7036_msg_1 : verwendet in
class CCI_7036_msg_2 {
  Nachricht: REQOTE 1.3b
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: 000, 10, 17, 200, 35, 999, CCI, OCR, Z60
  Prozesse: Bestellung einer technischen Konfiguration (MSB)
  Quelle: REQOTE_MIG_1_3b_20241001.pdf
}
CCI_7036 --> CCI_7036_msg_2 : verwendet in
class CCI_7036_proc_1 <<process>> {
  Bestellung einer technischen Konfiguration (MSB)
  Gesetze: MsbG, EnWG
  Zusammenfassung: Erläutere den Prozess zur Bestellung einer spezifischen technischen Konfiguration bei einem Messstellenbetreiber, beispielsweise für ein intelligentes Messsystem.
}
CCI_7036 ..> CCI_7036_proc_1 : eingebettet in
class CCI_7036_proc_2 <<process>> {
  Sperrung und Entsperrung eines Anschlusses
  Gesetze: StromGVV
  Zusammenfassung: Beschreibe den End-to-End-Prozess für die Sperrung und Wiederherstellung eines Netzanschlusses.
}
CCI_7036 ..> CCI_7036_proc_2 : eingebettet in
@enduml