@startuml
title Datenatlas – CCI:00034
class CCI_00034 {
  Name: Mengenumwerter
  Prozesse:
    - Bestellung einer technischen Konfiguration (MSB)
    - Sperrung und Entsperrung eines Anschlusses
}
class CCI_00034_msg_1 {
  Nachricht: QUOTES 1.3a
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: CCI
  Prozesse: Bestellung einer technischen Konfiguration (MSB), Sperrung und Entsperrung eines Anschlusses
  Quelle: QUOTES_MIG_1_3a_Fehlerkorrektur_20241213.pdf
}
CCI_00034 --> CCI_00034_msg_1 : verwendet in
class CCI_00034_proc_1 <<process>> {
  Bestellung einer technischen Konfiguration (MSB)
  Gesetze: MsbG, EnWG
  Zusammenfassung: Erläutere den Prozess zur Bestellung einer spezifischen technischen Konfiguration bei einem Messstellenbetreiber, beispielsweise für ein intelligentes Messsystem.
}
CCI_00034 ..> CCI_00034_proc_1 : eingebettet in
class CCI_00034_proc_2 <<process>> {
  Sperrung und Entsperrung eines Anschlusses
  Gesetze: StromGVV
  Zusammenfassung: Beschreibe den End-to-End-Prozess für die Sperrung und Wiederherstellung eines Netzanschlusses.
}
CCI_00034 ..> CCI_00034_proc_2 : eingebettet in
@enduml