@startuml
title Datenatlas – CNTRL:DE0104
class CNTRL_DE0104 {
  Name: Position des fehlerhaften Gruppendatenelements
}
class CNTRL_DE0104_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: DE, UNH, UNT
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
CNTRL_DE0104 --> CNTRL_DE0104_msg_1 : verwendet in
@enduml