@startuml
title Datenatlas – COM:0310
class COM_0310 {
  Name: Kommunikationsverbindung
  Prozesse:
    - Stammdatenänderung
}
class COM_0310_msg_1 {
  Nachricht: PARTIN 1.0e
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Nein
  Codes: COM, SG4
  Prozesse: Stammdatenänderung
  Quelle: PARTIN_MIG_1_0e_20241001.pdf
}
COM_0310 --> COM_0310_msg_1 : verwendet in
class COM_0310_proc_1 <<process>> {
  Stammdatenänderung
  Zusammenfassung: Wie wird eine Stammdatenänderung an einer Marktlokation, wie z.B.
}
COM_0310 ..> COM_0310_proc_1 : eingebettet in
@enduml