@startuml
title Datenatlas – COM:3155
class COM_3155 {
  Name: Art des Kommunikationsmittels, Code
  Prozesse:
    - Netznutzungsabrechnung
    - Messstellenbetriebsabrechnung
    - Anforderung und Übermittlung von Messwerten
    - Bestellung einer technischen Konfiguration (MSB)
    - Sperrung und Entsperrung eines Anschlusses
    - Stammdatenänderung
}
class COM_3155_msg_1 {
  Nachricht: INSRPT 1.1a
  Kontext: Beispiel:
  Pflichtfeld: Nein
  Codes: 512, 99, AJ, AL, COM, EM, FX, OCR, SG, SG3, SG5, SG6, TE
  Prozesse: Netznutzungsabrechnung
  Quelle: INSRPT_MIG_1_1a_außerordentliche_20240726.pdf
}
COM_3155 --> COM_3155_msg_1 : verwendet in
class COM_3155_msg_2 {
  Nachricht: INVOIC 2.8d
  Kontext: Segmentlayout
  Pflichtfeld: Nein
  Codes: 512, 99, AJ, AL, COM, EDI, EM, FX, OCR, SG, SG2, SG5, TE
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2.8d_Fehlerkorrektur_20250131.pdf
}
COM_3155 --> COM_3155_msg_2 : verwendet in
class COM_3155_msg_3 {
  Nachricht: MSCONS 2.4c
  Kontext: Beispiel:
  Pflichtfeld: Nein
  Codes: 100, 12, 512, 99, AJ, AL, COM, EM, FX, ID, MP, SG, SG2, SG4, TE
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_20231024.pdf
}
COM_3155 --> COM_3155_msg_3 : verwendet in
class COM_3155_msg_4 {
  Nachricht: ORDCHG 1.1
  Kontext: Beispiel:
  Pflichtfeld: Nein
  Codes: 512, 99, AJ, AL, COM, EM, FX, ID, MP, OCR, SG, SG3, SG6, TE
  Quelle: ORDCHG_MIG_1_1_außerordentliche_20240726.pdf
}
COM_3155 --> COM_3155_msg_4 : verwendet in
class COM_3155_msg_5 {
  Nachricht: ORDRSP 1.4
  Kontext: Segmentlayout
  Pflichtfeld: Nein
  Codes: 512, 99, AJ, AL, COM, EM, FX, ID, MP, OCR, SG, SG3, SG6, TE
  Prozesse: Bestellung einer technischen Konfiguration (MSB), Sperrung und Entsperrung eines Anschlusses
  Quelle: ORDRSP_MIG_1_4_20240619.pdf
}
COM_3155 --> COM_3155_msg_5 : verwendet in
class COM_3155_msg_6 {
  Nachricht: PARTIN 1.0e
  Kontext: Beispiel:
  Pflichtfeld: Nein
  Codes: 512, COM, EM, FX, OCR, SG, SG4, SG7, TE
  Prozesse: Stammdatenänderung
  Quelle: PARTIN_MIG_1_0e_20241001.pdf
}
COM_3155 --> COM_3155_msg_6 : verwendet in
class COM_3155_msg_7 {
  Nachricht: PRICAT 2.0d
  Kontext: 0150   SG4   C   5   O   1   2   CTA - COM
  Pflichtfeld: Nein
  Codes: 512, 99, AJ, AL, COM, CTA, EM, FX, ID, SG2, SG4, TE
  Prozesse: Netznutzungsabrechnung
  Quelle: PRICAT_MIG_2_0d_20240619.pdf
}
COM_3155 --> COM_3155_msg_7 : verwendet in
class COM_3155_msg_8 {
  Nachricht: QUOTES 1.3a
  Kontext: Segmentlayout
  Pflichtfeld: Nein
  Codes: 512, 99, AJ, AL, COM, EM, FX, ID, MP, OCR, SG, TE
  Prozesse: Bestellung einer technischen Konfiguration (MSB), Sperrung und Entsperrung eines Anschlusses
  Quelle: QUOTES_MIG_1_3a_20240619.pdf
}
COM_3155 --> COM_3155_msg_8 : verwendet in
class COM_3155_msg_9 {
  Nachricht: REMADV 2.9c
  Kontext: Segmentlayout
  Pflichtfeld: Nein
  Codes: 512, 99, AJ, AL, COM, EM, FX, ID, MP, OCR, SG1, SG3, TE
  Prozesse: Netznutzungsabrechnung
  Quelle: REMADV_MIG_2.9c_außerordentliche_20240726.pdf
}
COM_3155 --> COM_3155_msg_9 : verwendet in
class COM_3155_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
COM_3155 ..> COM_3155_proc_1 : eingebettet in
class COM_3155_proc_2 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
COM_3155 ..> COM_3155_proc_2 : eingebettet in
class COM_3155_proc_3 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
COM_3155 ..> COM_3155_proc_3 : eingebettet in
class COM_3155_proc_4 <<process>> {
  Bestellung einer technischen Konfiguration (MSB)
  Gesetze: MsbG, EnWG
  Zusammenfassung: Erläutere den Prozess zur Bestellung einer spezifischen technischen Konfiguration bei einem Messstellenbetreiber, beispielsweise für ein intelligentes Messsystem.
}
COM_3155 ..> COM_3155_proc_4 : eingebettet in
class COM_3155_proc_5 <<process>> {
  Sperrung und Entsperrung eines Anschlusses
  Gesetze: StromGVV
  Zusammenfassung: Beschreibe den End-to-End-Prozess für die Sperrung und Wiederherstellung eines Netzanschlusses.
}
COM_3155 ..> COM_3155_proc_5 : eingebettet in
class COM_3155_proc_6 <<process>> {
  Stammdatenänderung
  Zusammenfassung: Wie wird eine Stammdatenänderung an einer Marktlokation, wie z.B.
}
COM_3155 ..> COM_3155_proc_6 : eingebettet in
@enduml