@startuml
title Datenatlas – CONTRL:S011
class CONTRL_S011 {
  Name: Identifikation der Position eines fehlerhaften Datenelements
}
class CONTRL_S011_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: Bezeichner hat die Positionsnummer 1.
  Pflichtfeld: Ja
  Codes: DE, UNH, UNT
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
CONTRL_S011 --> CONTRL_S011_msg_1 : verwendet in
@enduml