@startuml
title Datenatlas – CONTRL:DE0062
class CONTRL_DE0062 {
  Name: Nachrichten-Referenznummer
}
class CONTRL_DE0062_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: Bezeichner hat die Positionsnummer 1.
  Pflichtfeld: Ja
  Codes: DE, UNH, UNT
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
CONTRL_DE0062 --> CONTRL_DE0062_msg_1 : verwendet in
@enduml