@startuml
title Datenatlas – CTA:00033
class CTA_00033 {
  Name: Ansprechpartner
  Prozesse:
    - Stammdatenänderung
}
class CTA_00033_msg_1 {
  Nachricht: PARTIN 1.0e
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: CTA
  Prozesse: Stammdatenänderung
  Quelle: PARTIN_MIG_1_0e_20241001.pdf
}
CTA_00033 --> CTA_00033_msg_1 : verwendet in
class CTA_00033_proc_1 <<process>> {
  Stammdatenänderung
  Zusammenfassung: Wie wird eine Stammdatenänderung an einer Marktlokation, wie z.B.
}
CTA_00033 ..> CTA_00033_proc_1 : eingebettet in
@enduml