@startuml
title Datenatlas – CUX:0430
class CUX_0430 {
  Name: Fälligkeitsdatum
  Prozesse:
    - Netznutzungsabrechnung
    - Messstellenbetriebsabrechnung
}
class CUX_0430_msg_1 {
  Nachricht: INVOIC 2.8d
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: 10, CUX, SG8
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2.8d_Fehlerkorrektur_20250131.pdf
}
CUX_0430 --> CUX_0430_msg_1 : verwendet in
class CUX_0430_msg_2 {
  Nachricht: INVOIC 2.8d.
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: 10, CUX, SG8
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2_8d__20240619.pdf
}
CUX_0430 --> CUX_0430_msg_2 : verwendet in
class CUX_0430_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
CUX_0430 ..> CUX_0430_proc_1 : eingebettet in
class CUX_0430_proc_2 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
CUX_0430 ..> CUX_0430_proc_2 : eingebettet in
@enduml