@startuml
title Datenatlas – DTM:0370
class DTM_0370 {
  Name: Beginn Messperiode
  Prozesse:
    - Anforderung und Übermittlung von Messwerten
}
class DTM_0370_msg_1 {
  Nachricht: MSCONS 2.4c
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Nein
  Codes: DTM
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_außerordentliche_20240726.pdf
}
DTM_0370 --> DTM_0370_msg_1 : verwendet in
class DTM_0370_proc_1 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
DTM_0370 ..> DTM_0370_proc_1 : eingebettet in
@enduml