@startuml
title Datenatlas – DTM:492
class DTM_492 {
  Name: Betrachtungszeitintervall
  Prozesse:
    - Netznutzungsabrechnung
}
class DTM_492_msg_1 {
  Nachricht: PRICAT 2.0d
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: 06, 19, 35, 492, 610, DTM
  Prozesse: Netznutzungsabrechnung
  Quelle: PRICAT_MIG_2_0d_20240619.pdf
}
DTM_492 --> DTM_492_msg_1 : verwendet in
class DTM_492_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
DTM_492 ..> DTM_492_proc_1 : eingebettet in
@enduml