@startuml
title Datenatlas – DTM:0210
class DTM_0210 {
  Name: Bilanzierungsmonat
  Prozesse:
    - Anforderung und Übermittlung von Messwerten
}
class DTM_0210_msg_1 {
  Nachricht: MSCONS 2.4c
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Nein
  Codes: DTM
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_außerordentliche_20240726.pdf
}
DTM_0210 --> DTM_0210_msg_1 : verwendet in
class DTM_0210_proc_1 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
DTM_0210 ..> DTM_0210_proc_1 : eingebettet in
@enduml