@startuml
title Datenatlas – EBD:E_0566
class EBD_E_0566 {
  Name: EBD Nr. E_0566 Rechnung Messstellenbetrieb mit iMS gegenüber dem NB prüfen
  Prozesse:
    - Messstellenbetriebsabrechnung
    - Netznutzungsabrechnung
}
class EBD_E_0566_msg_1 {
  Nachricht: REMADV 2.9c
  Kontext: Segmentlayout
  Pflichtfeld: Nein
  Codes: EBD, ESA, LF, MGV, MSB, NB, NN
  Prozesse: Messstellenbetriebsabrechnung, Netznutzungsabrechnung
  Quelle: REMADV_MIG_2.9c_20231024.pdf
}
EBD_E_0566 --> EBD_E_0566_msg_1 : verwendet in
class EBD_E_0566_proc_1 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
EBD_E_0566 ..> EBD_E_0566_proc_1 : eingebettet in
class EBD_E_0566_proc_2 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
EBD_E_0566 ..> EBD_E_0566_proc_2 : eingebettet in
@enduml