@startuml
title Datenatlas – EBD:E_0259
class EBD_E_0259 {
  Name: EBD Nr. E_0259 Rechnung verarbeiten Codeliste zur Prüfung der Abrechnung von Dienstleistungen zwischen MSB und MSB
  Prozesse:
    - Netznutzungsabrechnung
}
class EBD_E_0259_msg_1 {
  Nachricht: REMADV 2.9c
  Kontext: Segmentlayout
  Pflichtfeld: Nein
  Codes: EBD, ESA, LF, MGV, MSB, NB, NN
  Prozesse: Netznutzungsabrechnung
  Quelle: REMADV_MIG_2.9c_20231024.pdf
}
EBD_E_0259 --> EBD_E_0259_msg_1 : verwendet in
class EBD_E_0259_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
EBD_E_0259 ..> EBD_E_0259_proc_1 : eingebettet in
@enduml