@startuml
title Datenatlas – FEHLENDE TABELLE:0098
class FEHLENDE_TABELLE_0098 {
  Name: Segmentposition des fehlerhaften Datenelements / fehlerhaften Datenelements Datenelementgruppe
}
class FEHLENDE_TABELLE_0098_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: Nachrichten enthielt.
  Pflichtfeld: Nein
  Codes: 29, 32, UNA, UNB, UNZ
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
FEHLENDE_TABELLE_0098 --> FEHLENDE_TABELLE_0098_msg_1 : verwendet in
@enduml