@startuml
title Datenatlas – FII:0180
class FII_0180 {
  Name: Bankverbindung
  Prozesse:
    - Stammdatenänderung
}
class FII_0180_msg_1 {
  Nachricht: PARTIN 1.0e
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Nein
  Codes: 10, FII
  Prozesse: Stammdatenänderung
  Quelle: PARTIN_MIG_1_0e_20241001.pdf
}
FII_0180 --> FII_0180_msg_1 : verwendet in
class FII_0180_proc_1 <<process>> {
  Stammdatenänderung
  Zusammenfassung: Wie wird eine Stammdatenänderung an einer Marktlokation, wie z.B.
}
FII_0180 ..> FII_0180_proc_1 : eingebettet in
@enduml