@startuml
title Datenatlas – IDE:E_1009
class IDE_E_1009 {
  Name: EBD Nr. E_1009_erneut Rechnung einer sonstigen Leistung prüfen. Dies kann für die Rechnung zur Beauftragung der Unterbrechung der Anschlussnutzung (Sperren) oder die Rechnung zu Verzugskosten beinhalten (Gas).
  Prozesse:
    - Sperrung und Entsperrung eines Anschlusses
    - Netznutzungsabrechnung
}
class IDE_E_1009_msg_1 {
  Nachricht: REMADV 2.9c
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: EBD, ESA, LF, MGV, MSB, NB, NN
  Prozesse: Sperrung und Entsperrung eines Anschlusses, Netznutzungsabrechnung
  Quelle: REMADV_MIG_2.9c_20231024.pdf
}
IDE_E_1009 --> IDE_E_1009_msg_1 : verwendet in
class IDE_E_1009_proc_1 <<process>> {
  Sperrung und Entsperrung eines Anschlusses
  Gesetze: StromGVV
  Zusammenfassung: Beschreibe den End-to-End-Prozess für die Sperrung und Wiederherstellung eines Netzanschlusses.
}
IDE_E_1009 ..> IDE_E_1009_proc_1 : eingebettet in
class IDE_E_1009_proc_2 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
IDE_E_1009 ..> IDE_E_1009_proc_2 : eingebettet in
@enduml