@startuml
title Datenatlas – IDE:1009
class IDE_1009 {
  Name: Nummer der Organisation, welche die Code Liste verwaltet
  Prozesse:
    - Anforderung und Übermittlung von Messwerten
}
class IDE_1009_msg_1 {
  Nachricht: MSCONS 2.4c
  Kontext: Ersatzprofilbestimmung und Skalierung.
  Pflichtfeld: Ja
  Codes: OCR, ZQ8, ZQ9, ZR0, ZS0
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_außerordentliche_20240726.pdf
}
IDE_1009 --> IDE_1009_msg_1 : verwendet in
class IDE_1009_proc_1 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
IDE_1009 ..> IDE_1009_proc_1 : eingebettet in
@enduml