@startuml
title Datenatlas – IDE:E_0266
class IDE_E_0266 {
  Name: EBD Nr. E_0266 zur erneuten Prüfung der Abrechnung einer für den ESA erbrachten Leistung
  Prozesse:
    - Netznutzungsabrechnung
}
class IDE_E_0266_msg_1 {
  Nachricht: REMADV 2.9c
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: EBD, ESA, LF, MGV, MSB, NB, NN
  Prozesse: Netznutzungsabrechnung
  Quelle: REMADV_MIG_2.9c_20231024.pdf
}
IDE_E_0266 --> IDE_E_0266_msg_1 : verwendet in
class IDE_E_0266_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
IDE_E_0266 ..> IDE_E_0266_proc_1 : eingebettet in
@enduml