@startuml
title Datenatlas – INVOIC:SG7
class INVOIC_SG7 {
  Name: Währung
  Prozesse:
    - Netznutzungsabrechnung
    - Messstellenbetriebsabrechnung
}
class INVOIC_SG7_msg_1 {
  Nachricht: INVOIC 2.8d
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: 99, MIG, SG7
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2.8d_Fehlerkorrektur_20250131.pdf
}
INVOIC_SG7 --> INVOIC_SG7_msg_1 : verwendet in
class INVOIC_SG7_msg_2 {
  Nachricht: INVOIC 2.8d.
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: 99, MIG, SG7
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2_8d__20240619.pdf
}
INVOIC_SG7 --> INVOIC_SG7_msg_2 : verwendet in
class INVOIC_SG7_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
INVOIC_SG7 ..> INVOIC_SG7_proc_1 : eingebettet in
class INVOIC_SG7_proc_2 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
INVOIC_SG7 ..> INVOIC_SG7_proc_2 : eingebettet in
@enduml