@startuml
title Datenatlas – LIN:00016
class LIN_00016 {
  Name: Positionsdaten
  Prozesse:
    - Netznutzungsabrechnung
}
class LIN_00016_msg_1 {
  Nachricht: PRICAT 2.0d
  Kontext: 1310   SG36   C   R   999999   999999   2   LIN - PIA - IMD - SG40
  Pflichtfeld: Ja
  Codes: LIN
  Prozesse: Netznutzungsabrechnung
  Quelle: PRICAT_MIG_2_0d_20240619.pdf
}
LIN_00016 --> LIN_00016_msg_1 : verwendet in
class LIN_00016_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
LIN_00016 ..> LIN_00016_proc_1 : eingebettet in
@enduml