@startuml
title Datenatlas – LIN:C212
class LIN_C212 {
  Name: Waren-/Leistungsnummer, Identifikation
  Prozesse:
    - Netznutzungsabrechnung
    - Messstellenbetriebsabrechnung
    - Bestellung einer technischen Konfiguration (MSB)
    - Sperrung und Entsperrung eines Anschlusses
}
class LIN_C212_msg_1 {
  Nachricht: INVOIC 2.8d
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: 35, ID, LIN, OCR, Z01, Z09
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2.8d_Fehlerkorrektur_20250131.pdf
}
LIN_C212 --> LIN_C212_msg_1 : verwendet in
class LIN_C212_msg_2 {
  Nachricht: INVOIC 2.8d.
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: 35, ID, LIN, Z01, Z09
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2_8d__20240619.pdf
}
LIN_C212 --> LIN_C212_msg_2 : verwendet in
class LIN_C212_msg_3 {
  Nachricht: PRICAT 2.0d
  Kontext: Bemerkung:
  Pflichtfeld: Ja
  Codes: 35, ID, LIN, OCR, Z09
  Prozesse: Netznutzungsabrechnung
  Quelle: PRICAT_MIG_2_0d_20240619.pdf
}
LIN_C212 --> LIN_C212_msg_3 : verwendet in
class LIN_C212_msg_4 {
  Nachricht: QUOTES 1.3a
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: 000, 200, 35, EDI, ID, LIN, OCR, Z01, Z09
  Prozesse: Bestellung einer technischen Konfiguration (MSB), Sperrung und Entsperrung eines Anschlusses
  Quelle: QUOTES_MIG_1_3a_20240619.pdf
}
LIN_C212 --> LIN_C212_msg_4 : verwendet in
class LIN_C212_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
LIN_C212 ..> LIN_C212_proc_1 : eingebettet in
class LIN_C212_proc_2 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
LIN_C212 ..> LIN_C212_proc_2 : eingebettet in
class LIN_C212_proc_3 <<process>> {
  Bestellung einer technischen Konfiguration (MSB)
  Gesetze: MsbG, EnWG
  Zusammenfassung: Erläutere den Prozess zur Bestellung einer spezifischen technischen Konfiguration bei einem Messstellenbetreiber, beispielsweise für ein intelligentes Messsystem.
}
LIN_C212 ..> LIN_C212_proc_3 : eingebettet in
class LIN_C212_proc_4 <<process>> {
  Sperrung und Entsperrung eines Anschlusses
  Gesetze: StromGVV
  Zusammenfassung: Beschreibe den End-to-End-Prozess für die Sperrung und Wiederherstellung eines Netzanschlusses.
}
LIN_C212 ..> LIN_C212_proc_4 : eingebettet in
@enduml