@startuml
title Datenatlas – LOC:LOC
class LOC_LOC {
  Name: Ortsangabe, Qualifier
  Prozesse:
    - Anforderung und Übermittlung von Messwerten
}
class LOC_LOC_msg_1 {
  Nachricht: MSCONS 2.4c
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: 107, 172, 204, 35, LOC, OCR, SG5, SG6, Z06
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_außerordentliche_20240726.pdf
}
LOC_LOC --> LOC_LOC_msg_1 : verwendet in
class LOC_LOC_proc_1 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
LOC_LOC ..> LOC_LOC_proc_1 : eingebettet in
@enduml