@startuml
title Datenatlas – LOC:C519
class LOC_C519 {
  Name: Zugehöriger Ort 1, Identifikation
  Prozesse:
    - Anforderung und Übermittlung von Messwerten
}
class LOC_C519_msg_1 {
  Nachricht: MSCONS 2.4c
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: 237, 25, 35, LOC, OCR, SG5, SG6
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_außerordentliche_20240726.pdf
}
LOC_C519 --> LOC_C519_msg_1 : verwendet in
class LOC_C519_proc_1 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
LOC_C519 ..> LOC_C519_proc_1 : eingebettet in
@enduml