@startuml
title Datenatlas – LOC:00029
class LOC_00029 {
  Name: Meldepunkt
  Prozesse:
    - Netznutzungsabrechnung
    - Messstellenbetriebsabrechnung
}
class LOC_00029_msg_1 {
  Nachricht: INVOIC 2.8d
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Nein
  Codes: 25, 99, LOC, SG2
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2.8d_Fehlerkorrektur_20250131.pdf
}
LOC_00029 --> LOC_00029_msg_1 : verwendet in
class LOC_00029_msg_2 {
  Nachricht: INVOIC 2.8d.
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Nein
  Codes: 25, 99, LOC, SG2
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2_8d__20240619.pdf
}
LOC_00029 --> LOC_00029_msg_2 : verwendet in
class LOC_00029_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
LOC_00029 ..> LOC_00029_proc_1 : eingebettet in
class LOC_00029_proc_2 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
LOC_00029 ..> LOC_00029_proc_2 : eingebettet in
@enduml