@startuml
title Datenatlas – MOA:C516
class MOA_C516 {
  Name: Geldbetrag
  Prozesse:
    - Netznutzungsabrechnung
    - Messstellenbetriebsabrechnung
    - Bestellung einer technischen Konfiguration (MSB)
    - Sperrung und Entsperrung eines Anschlusses
}
class MOA_C516_msg_1 {
  Nachricht: INVOIC 2.8d
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: 25, 30, 35, 536, MOA
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2.8d_Fehlerkorrektur_20250131.pdf
}
MOA_C516 --> MOA_C516_msg_1 : verwendet in
class MOA_C516_msg_2 {
  Nachricht: INVOIC 2.8d.
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: 30, 35, MOA, OCR, Z01
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2_8d__20240619.pdf
}
MOA_C516 --> MOA_C516_msg_2 : verwendet in
class MOA_C516_msg_3 {
  Nachricht: ORDRSP 1.4
  Kontext: Beispiel:
  Pflichtfeld: Nein
  Codes: 12, 35, MOA, Z02
  Prozesse: Bestellung einer technischen Konfiguration (MSB), Sperrung und Entsperrung eines Anschlusses
  Quelle: ORDRSP_MIG_1_4_20240619.pdf
}
MOA_C516 --> MOA_C516_msg_3 : verwendet in
class MOA_C516_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
MOA_C516 ..> MOA_C516_proc_1 : eingebettet in
class MOA_C516_proc_2 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
MOA_C516 ..> MOA_C516_proc_2 : eingebettet in
class MOA_C516_proc_3 <<process>> {
  Bestellung einer technischen Konfiguration (MSB)
  Gesetze: MsbG, EnWG
  Zusammenfassung: Erläutere den Prozess zur Bestellung einer spezifischen technischen Konfiguration bei einem Messstellenbetreiber, beispielsweise für ein intelligentes Messsystem.
}
MOA_C516 ..> MOA_C516_proc_3 : eingebettet in
class MOA_C516_proc_4 <<process>> {
  Sperrung und Entsperrung eines Anschlusses
  Gesetze: StromGVV
  Zusammenfassung: Beschreibe den End-to-End-Prozess für die Sperrung und Wiederherstellung eines Netzanschlusses.
}
MOA_C516 ..> MOA_C516_proc_4 : eingebettet in
@enduml