@startuml
title Datenatlas – MOA:1250
class MOA_1250 {
  Name: Gesamtzu -   oder abschlagsbetrag
  Prozesse:
    - Netznutzungsabrechnung
    - Messstellenbetriebsabrechnung
}
class MOA_1250_msg_1 {
  Nachricht: INVOIC 2.8d.
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: 99, MOA
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2_8d__20240619.pdf
}
MOA_1250 --> MOA_1250_msg_1 : verwendet in
class MOA_1250_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
MOA_1250 ..> MOA_1250_proc_1 : eingebettet in
class MOA_1250_proc_2 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
MOA_1250 ..> MOA_1250_proc_2 : eingebettet in
@enduml