@startuml
title Datenatlas – NAD:0230
class NAD_0230 {
  Name: Adresse der Leistungserbringung
  Prozesse:
    - Netznutzungsabrechnung
    - Messstellenbetriebsabrechnung
}
class NAD_0230_msg_1 {
  Nachricht: INVOIC 2.8d
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: NAD
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2.8d_Fehlerkorrektur_20250131.pdf
}
NAD_0230 --> NAD_0230_msg_1 : verwendet in
class NAD_0230_msg_2 {
  Nachricht: INVOIC 2.8d.
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: NAD
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2_8d__20240619.pdf
}
NAD_0230 --> NAD_0230_msg_2 : verwendet in
class NAD_0230_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
NAD_0230 ..> NAD_0230_proc_1 : eingebettet in
class NAD_0230_proc_2 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
NAD_0230 ..> NAD_0230_proc_2 : eingebettet in
@enduml