@startuml
title Datenatlas – NAD:0080
class NAD_0080 {
  Name: ID Absender
  Prozesse:
    - Netznutzungsabrechnung
}
class NAD_0080_msg_1 {
  Nachricht: INSRPT 1.1a
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: 99, ID, MP, NAD, SG3
  Prozesse: Netznutzungsabrechnung
  Quelle: INSRPT_MIG_1_1a_außerordentliche_20240726.pdf
}
NAD_0080 --> NAD_0080_msg_1 : verwendet in
class NAD_0080_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
NAD_0080 ..> NAD_0080_proc_1 : eingebettet in
@enduml