@startuml
title Datenatlas – ORDCHG:1153
class ORDCHG_1153 {
  Name: Referenz, Qualifier
}
class ORDCHG_1153_msg_1 {
  Nachricht: ORDCHG 1.1
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: 35, 70, MIG, ON, RFF, SG1
  Quelle: ORDCHG_MIG_1_1_20230331.pdf
}
ORDCHG_1153 --> ORDCHG_1153_msg_1 : verwendet in
@enduml