@startuml
title Datenatlas – ORDCHG:2005
class ORDCHG_2005 {
  Name: Datums -   oder Uhrzeit -   oder  Zeitspannen - Funktion, Qualifier
}
class ORDCHG_2005_msg_1 {
  Nachricht: ORDCHG 1.1
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: 137, 303, 35, DTM, MIG
  Quelle: ORDCHG_MIG_1_1_20230331.pdf
}
ORDCHG_2005 --> ORDCHG_2005_msg_1 : verwendet in
@enduml