@startuml
title Datenatlas – PARTIN:MAXWDH
class PARTIN_MAXWDH {
  Name: BDEW
  Prozesse:
    - Stammdatenänderung
}
class PARTIN_MAXWDH_msg_1 {
  Nachricht: PARTIN 1.0e
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: MIG
  Prozesse: Stammdatenänderung
  Quelle: PARTIN_MIG_1_0e_20241001.pdf
}
PARTIN_MAXWDH --> PARTIN_MAXWDH_msg_1 : verwendet in
class PARTIN_MAXWDH_proc_1 <<process>> {
  Stammdatenänderung
  Zusammenfassung: Wie wird eine Stammdatenänderung an einer Marktlokation, wie z.B.
}
PARTIN_MAXWDH ..> PARTIN_MAXWDH_proc_1 : eingebettet in
@enduml