@startuml
title Datenatlas – PCD:5482
class PCD_5482 {
  Name: Prozentsatz
  Prozesse:
    - Netznutzungsabrechnung
    - Messstellenbetriebsabrechnung
}
class PCD_5482_msg_1 {
  Nachricht: INVOIC 2.8d
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: 10, 30, OCR, PCD
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2.8d_Fehlerkorrektur_20250131.pdf
}
PCD_5482 --> PCD_5482_msg_1 : verwendet in
class PCD_5482_msg_2 {
  Nachricht: INVOIC 2.8d.
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: 10, 30, OCR, PCD
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2_8d__20240619.pdf
}
PCD_5482 --> PCD_5482_msg_2 : verwendet in
class PCD_5482_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
PCD_5482 ..> PCD_5482_proc_1 : eingebettet in
class PCD_5482_proc_2 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
PCD_5482 ..> PCD_5482_proc_2 : eingebettet in
@enduml