@startuml
title Datenatlas – PGI:1310
class PGI_1310 {
  Name: SG36
  Prozesse:
    - Netznutzungsabrechnung
}
class PGI_1310_msg_1 {
  Nachricht: PRICAT 2.0d
  Kontext: 1310   SG36   C   R   999999   999999   2   LIN - PIA - IMD - SG40
  Pflichtfeld: Ja
  Codes: IMD, LIN, PGI, PIA
  Prozesse: Netznutzungsabrechnung
  Quelle: PRICAT_MIG_2_0d_20240619.pdf
}
PGI_1310 --> PGI_1310_msg_1 : verwendet in
class PGI_1310_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
PGI_1310 ..> PGI_1310_proc_1 : eingebettet in
@enduml