@startuml
title Datenatlas – PIA:1230
class PIA_1230 {
  Name: SG28
  Prozesse:
    - Bestellung einer technischen Konfiguration (MSB)
    - Sperrung und Entsperrung eines Anschlusses
}
class PIA_1230_msg_1 {
  Nachricht: QUOTES 1.3a
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Nein
  Codes: 06, 19, 25, 87, 999, ID, PIA, UN
  Prozesse: Bestellung einer technischen Konfiguration (MSB), Sperrung und Entsperrung eines Anschlusses
  Quelle: QUOTES_MIG_1_3a_20240619.pdf
}
PIA_1230 --> PIA_1230_msg_1 : verwendet in
class PIA_1230_proc_1 <<process>> {
  Bestellung einer technischen Konfiguration (MSB)
  Gesetze: MsbG, EnWG
  Zusammenfassung: Erläutere den Prozess zur Bestellung einer spezifischen technischen Konfiguration bei einem Messstellenbetreiber, beispielsweise für ein intelligentes Messsystem.
}
PIA_1230 ..> PIA_1230_proc_1 : eingebettet in
class PIA_1230_proc_2 <<process>> {
  Sperrung und Entsperrung eines Anschlusses
  Gesetze: StromGVV
  Zusammenfassung: Beschreibe den End-to-End-Prozess für die Sperrung und Wiederherstellung eines Netzanschlusses.
}
PIA_1230 ..> PIA_1230_proc_2 : eingebettet in
@enduml