@startuml
title Datenatlas – PRC:E_0259
class PRC_E_0259 {
  Name: EBD Nr. E_0259 Rechnung verarbeiten Codeliste zur Prüfung der Abrechnung von Dienstleistungen zwischen MSB und MSB
  Prozesse:
    - Netznutzungsabrechnung
}
class PRC_E_0259_msg_1 {
  Nachricht: REMADV 2.9c
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: EBD, ESA, LF, MGV, MSB, NB, NN
  Prozesse: Netznutzungsabrechnung
  Quelle: REMADV_MIG_2.9c_20231024.pdf
}
PRC_E_0259 --> PRC_E_0259_msg_1 : verwendet in
class PRC_E_0259_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
PRC_E_0259 ..> PRC_E_0259_proc_1 : eingebettet in
@enduml