@startuml
title Datenatlas – PRC:G_0084
class PRC_G_0084 {
  Name: Codeliste Gas Nr. G_0084 Codeliste zur Prüfung Ablehnung der Rechnung vom MSBN an den MSBA
  Prozesse:
    - Netznutzungsabrechnung
}
class PRC_G_0084_msg_1 {
  Nachricht: REMADV 2.9c
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: EBD, ESA, LF, MGV, MSB, NB, NN
  Prozesse: Netznutzungsabrechnung
  Quelle: REMADV_MIG_2.9c_20231024.pdf
}
PRC_G_0084 --> PRC_G_0084_msg_1 : verwendet in
class PRC_G_0084_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
PRC_G_0084 ..> PRC_G_0084_proc_1 : eingebettet in
@enduml