@startuml
title Datenatlas – PRD:C273
class PRD_C273 {
  Name: Produkt-/<br>Leistungsbeschreibung
  Prozesse:
    - Netznutzungsabrechnung
}
class PRD_C273_msg_1 {
  Nachricht: PRICAT 2.0d
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: 000, 17, 23, 256, 31, 60, POG, Z08, Z09, Z10, Z11, Z31, Z32, Z41
  Prozesse: Netznutzungsabrechnung
  Quelle: PRICAT_MIG_2_0d_20240619.pdf
}
PRD_C273 --> PRD_C273_msg_1 : verwendet in
class PRD_C273_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
PRD_C273 ..> PRD_C273_proc_1 : eingebettet in
@enduml