@startuml
title Datenatlas – PRI:6411
class PRI_6411 {
  Name: Maßeinheit, Code
  Prozesse:
    - Netznutzungsabrechnung
    - Messstellenbetriebsabrechnung
    - Bestellung einer technischen Konfiguration (MSB)
    - Sperrung und Entsperrung eines Anschlusses
}
class PRI_6411_msg_1 {
  Nachricht: INVOIC 2.8d
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: 15, 25, ANN, CAL, DAY, MON, OCR, PRI
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2.8d_Fehlerkorrektur_20250131.pdf
}
PRI_6411 --> PRI_6411_msg_1 : verwendet in
class PRI_6411_msg_2 {
  Nachricht: INVOIC 2.8d.
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: 15, 25, ANN, CAL, DAY, MON, OCR, PRI
  Prozesse: Netznutzungsabrechnung, Messstellenbetriebsabrechnung
  Quelle: INVOIC_MIG_2_8d__20240619.pdf
}
PRI_6411 --> PRI_6411_msg_2 : verwendet in
class PRI_6411_msg_3 {
  Nachricht: PRICAT 2.0d
  Kontext: Es handelt sich um einen Nettopreis ohne USt. - Anteil.
  Pflichtfeld: Ja
  Codes: 100, 15, ANN, CAL, IMD, LIN, OCR, PGI, PIA, PRI
  Prozesse: Netznutzungsabrechnung
  Quelle: PRICAT_MIG_2_0d_20240619.pdf
}
PRI_6411 --> PRI_6411_msg_3 : verwendet in
class PRI_6411_msg_4 {
  Nachricht: QUOTES 1.3a
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: 15, 99, CAL, DAY, OCR, PRI, Z01, Z02, Z03
  Prozesse: Bestellung einer technischen Konfiguration (MSB), Sperrung und Entsperrung eines Anschlusses
  Quelle: QUOTES_MIG_1_3a_20240619.pdf
}
PRI_6411 --> PRI_6411_msg_4 : verwendet in
class PRI_6411_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
PRI_6411 ..> PRI_6411_proc_1 : eingebettet in
class PRI_6411_proc_2 <<process>> {
  Messstellenbetriebsabrechnung
  Gesetze: MsbG
  Zusammenfassung: Beschreibe den Prozess der Abrechnung von Messstellenbetriebsleistungen.
}
PRI_6411 ..> PRI_6411_proc_2 : eingebettet in
class PRI_6411_proc_3 <<process>> {
  Bestellung einer technischen Konfiguration (MSB)
  Gesetze: MsbG, EnWG
  Zusammenfassung: Erläutere den Prozess zur Bestellung einer spezifischen technischen Konfiguration bei einem Messstellenbetreiber, beispielsweise für ein intelligentes Messsystem.
}
PRI_6411 ..> PRI_6411_proc_3 : eingebettet in
class PRI_6411_proc_4 <<process>> {
  Sperrung und Entsperrung eines Anschlusses
  Gesetze: StromGVV
  Zusammenfassung: Beschreibe den End-to-End-Prozess für die Sperrung und Wiederherstellung eines Netzanschlusses.
}
PRI_6411 ..> PRI_6411_proc_4 : eingebettet in
@enduml