@startuml
title Datenatlas – QUOTES:EBENE
class QUOTES_EBENE {
  Name: Zähler
  Prozesse:
    - Bestellung einer technischen Konfiguration (MSB)
    - Sperrung und Entsperrung eines Anschlusses
}
class QUOTES_EBENE_msg_1 {
  Nachricht: QUOTES 1.3a
  Kontext: Segmentlayout
  Pflichtfeld: Ja
  Codes: MIG
  Prozesse: Bestellung einer technischen Konfiguration (MSB), Sperrung und Entsperrung eines Anschlusses
  Quelle: QUOTES_MIG_1_3a_20240619.pdf
}
QUOTES_EBENE --> QUOTES_EBENE_msg_1 : verwendet in
class QUOTES_EBENE_proc_1 <<process>> {
  Bestellung einer technischen Konfiguration (MSB)
  Gesetze: MsbG, EnWG
  Zusammenfassung: Erläutere den Prozess zur Bestellung einer spezifischen technischen Konfiguration bei einem Messstellenbetreiber, beispielsweise für ein intelligentes Messsystem.
}
QUOTES_EBENE ..> QUOTES_EBENE_proc_1 : eingebettet in
class QUOTES_EBENE_proc_2 <<process>> {
  Sperrung und Entsperrung eines Anschlusses
  Gesetze: StromGVV
  Zusammenfassung: Beschreibe den End-to-End-Prozess für die Sperrung und Wiederherstellung eines Netzanschlusses.
}
QUOTES_EBENE ..> QUOTES_EBENE_proc_2 : eingebettet in
@enduml