@startuml
title Datenatlas – RFF:00007
class RFF_00007 {
  Name: Prüfidentifikator
  Prozesse:
    - Netznutzungsabrechnung
}
class RFF_00007_msg_1 {
  Nachricht: APERAK 2.1i
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: ID, MP, RFF, SG3
  Quelle: APERAK_MIG_2_1i_20240619.pdf
}
RFF_00007 --> RFF_00007_msg_1 : verwendet in
class RFF_00007_msg_2 {
  Nachricht: INSRPT 1.1a
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: 99, RFF, SG4
  Prozesse: Netznutzungsabrechnung
  Quelle: INSRPT_MIG_1_1a_außerordentliche_20240726.pdf
}
RFF_00007 --> RFF_00007_msg_2 : verwendet in
class RFF_00007_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
RFF_00007 ..> RFF_00007_proc_1 : eingebettet in
@enduml