@startuml
title Datenatlas – RFF:0070
class RFF_0070 {
  Name: Vorgängerversion
  Prozesse:
    - Stammdatenänderung
}
class RFF_0070_msg_1 {
  Nachricht: PARTIN 1.0e
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: ID, MP, RFF, SG2
  Prozesse: Stammdatenänderung
  Quelle: PARTIN_MIG_1_0e_20241001.pdf
}
RFF_0070 --> RFF_0070_msg_1 : verwendet in
class RFF_0070_proc_1 <<process>> {
  Stammdatenänderung
  Zusammenfassung: Wie wird eine Stammdatenänderung an einer Marktlokation, wie z.B.
}
RFF_0070 ..> RFF_0070_proc_1 : eingebettet in
@enduml