@startuml
title Datenatlas – RNG:6167
class RNG_6167 {
  Name: Wertebereich, Qualifier
  Prozesse:
    - Netznutzungsabrechnung
}
class RNG_6167_msg_1 {
  Nachricht: PRICAT 2.0d
  Kontext: Segmentlayout
  Pflichtfeld: Nein
  Codes: 10, 100, 18, ID, KWH, RNG
  Prozesse: Netznutzungsabrechnung
  Quelle: PRICAT_MIG_2_0d_20240619.pdf
}
RNG_6167 --> RNG_6167_msg_1 : verwendet in
class RNG_6167_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
RNG_6167 ..> RNG_6167_proc_1 : eingebettet in
@enduml