@startuml
title Datenatlas – SG5:NAD
class SG5_NAD {
  Name: Name und Adresse
  Prozesse:
    - Anforderung und Übermittlung von Messwerten
}
class SG5_NAD_msg_1 {
  Nachricht: MSCONS 2.4c
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: 15, DED, DP, NAD, OCR, SG5, Z15
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_20231024.pdf
}
SG5_NAD --> SG5_NAD_msg_1 : verwendet in
class SG5_NAD_proc_1 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
SG5_NAD ..> SG5_NAD_proc_1 : eingebettet in
@enduml