@startuml
title Datenatlas – UCF:3055
class UCF_3055 {
  Name: Code list responsible agency code
}
class UCF_3055_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: Gruppendatenelement fehlt.
  Pflichtfeld: Ja
  Codes: 13, 16
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
UCF_3055 --> UCF_3055_msg_1 : verwendet in
@enduml