@startuml
title Datenatlas – UCI:C901
class UCI_C901 {
  Name: STATUS DER ÜBERTRAGUNGSDATEI
}
class UCI_C901_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: (vorgenommene Aktion) der Übertragungsdatei.
  Pflichtfeld: Ja
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
UCI_C901 --> UCI_C901_msg_1 : verwendet in
@enduml