@startuml
title Datenatlas – UCI:9321
class UCI_9321 {
  Name: Statusgrund, codiert
}
class UCI_9321_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: Empfänger abweicht.
  Pflichtfeld: Ja
  Codes: 12
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
UCI_9321 --> UCI_9321_msg_1 : verwendet in
@enduml