@startuml
title Datenatlas – UCM:S009
class UCM_S009 {
  Name: Nachrichten - Kennung
}
class UCM_S009_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: 0030   SG1   C   999999   D   999999   1   UCM - SG2
  Pflichtfeld: Ja
  Codes: 12, 14, MIG, SG1, SG2, UCM, UN, XYZ
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
UCM_S009 --> UCM_S009_msg_1 : verwendet in
@enduml