@startuml
title Datenatlas – UCM:DE0062
class UCM_DE0062 {
  Name: Nachrichten-Referenznummer
}
class UCM_DE0062_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: S011: Identifikation der Position eines fehlerhaften   Datenelements.
  Pflichtfeld: Ja
  Codes: 12, EDI, OCR, UCM, UN, UNH, UNT, XYZ
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
UCM_DE0062 --> UCM_DE0062_msg_1 : verwendet in
@enduml