@startuml
title Datenatlas – UNB:0031
class UNB_0031 {
  Name: Empfängerpasswort
  Prozesse:
    - Anforderung und Übermittlung von Messwerten
}
class UNB_0031_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: Empfänger bereits bekannt).
  Pflichtfeld: Ja
  Codes: 26, 28, UNB, UNZ
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
UNB_0031 --> UNB_0031_msg_1 : verwendet in
class UNB_0031_msg_2 {
  Nachricht: MSCONS 2.4c
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: 10, 14, 20, 23, 24, 52, TL, UNB
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_20231024.pdf
}
UNB_0031 --> UNB_0031_msg_2 : verwendet in
class UNB_0031_proc_1 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
UNB_0031 ..> UNB_0031_proc_1 : eingebettet in
@enduml