@startuml
title Datenatlas – UNB:S005
class UNB_S005 {
  Name: Übertragungsdatum
}
class UNB_S005_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: bei Empfänger nicht bekannt).
  Pflichtfeld: Ja
  Codes: 23, 25, ID, MP
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
UNB_S005 --> UNB_S005_msg_1 : verwendet in
@enduml