@startuml
title Datenatlas – UNBEKANNT:0104
class UNBEKANNT_0104 {
  Name: Position des fehlerhaften Gruppendatenelements
}
class UNBEKANNT_0104_msg_1 {
  Nachricht: CONTRL 2.0b
  Kontext: Beispiel:
  Pflichtfeld: Nein
  Codes: 38, 39, 40, OCR
  Quelle: CONTRL_MIG_2_0b_außerordentliche_20240726.pdf
}
UNBEKANNT_0104 --> UNBEKANNT_0104_msg_1 : verwendet in
@enduml