@startuml
title Datenatlas – UNH:0010
class UNH_0010 {
  Name: Nachrichtenkopfsegment
  Prozesse:
    - Anforderung und Übermittlung von Messwerten
}
class UNH_0010_msg_1 {
  Nachricht: MSCONS 2.4c
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: UNH
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_außerordentliche_20240726.pdf
}
UNH_0010 --> UNH_0010_msg_1 : verwendet in
class UNH_0010_proc_1 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
UNH_0010 ..> UNH_0010_proc_1 : eingebettet in
@enduml