@startuml
title Datenatlas – UNT:0054
class UNT_0054 {
  Name: Freigabenummer des Nachrichtentyps
  Prozesse:
    - Anforderung und Übermittlung von Messwerten
}
class UNT_0054_msg_1 {
  Nachricht: MSCONS 2.4c
  Kontext: Konverter vergeben.
  Pflichtfeld: Ja
  Codes: 35, UN, UNT
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_außerordentliche_20240726.pdf
}
UNT_0054 --> UNT_0054_msg_1 : verwendet in
class UNT_0054_proc_1 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
UNT_0054 ..> UNT_0054_proc_1 : eingebettet in
@enduml