@startuml
title Datenatlas – UNT:0070
class UNT_0070 {
  Name: Übermittlungsfolgenummer
  Prozesse:
    - Anforderung und Übermittlung von Messwerten
}
class UNT_0070_msg_1 {
  Nachricht: MSCONS 2.4c
  Kontext: Konverter vergeben.
  Pflichtfeld: Ja
  Codes: 35, UN, UNT
  Prozesse: Anforderung und Übermittlung von Messwerten
  Quelle: MSCONS_MIG_2_4c_außerordentliche_20240726.pdf
}
UNT_0070 --> UNT_0070_msg_1 : verwendet in
class UNT_0070_proc_1 <<process>> {
  Anforderung und Übermittlung von Messwerten
  Gesetze: MsbG
  Zusammenfassung: Wie kann ein Marktpartner (z.B.
}
UNT_0070 ..> UNT_0070_proc_1 : eingebettet in
@enduml