@startuml
title Datenatlas – UNT:00059
class UNT_00059 {
  Name: Nachrichten - Endesegment
  Prozesse:
    - Stammdatenänderung
}
class UNT_00059_msg_1 {
  Nachricht: PARTIN 1.0e
  Kontext: Nachrichtenstruktur
  Pflichtfeld: Ja
  Codes: 01, 10, 67, UN, UNT
  Prozesse: Stammdatenänderung
  Quelle: PARTIN_MIG_1_0e_20241001.pdf
}
UNT_00059 --> UNT_00059_msg_1 : verwendet in
class UNT_00059_proc_1 <<process>> {
  Stammdatenänderung
  Zusammenfassung: Wie wird eine Stammdatenänderung an einer Marktlokation, wie z.B.
}
UNT_00059 ..> UNT_00059_proc_1 : eingebettet in
@enduml