@startuml
title Datenatlas – UNT:00026
class UNT_00026 {
  Name: Nachrichten - Endesegment
  Prozesse:
    - Netznutzungsabrechnung
}
class UNT_00026_msg_1 {
  Nachricht: INSRPT 1.1a
  Kontext: 0320   SG8   C   R   999   1   3   NAD - LOC - RFF
  Pflichtfeld: Ja
  Codes: 07, 26, 31, UN, UNT
  Prozesse: Netznutzungsabrechnung
  Quelle: INSRPT_MIG_1_1a_außerordentliche_20240726.pdf
}
UNT_00026 --> UNT_00026_msg_1 : verwendet in
class UNT_00026_msg_2 {
  Nachricht: PRICAT 2.0d
  Kontext: 1310   SG36   C   R   999999   999999   2   LIN - PIA - IMD - SG40
  Pflichtfeld: Ja
  Codes: 06, 19, 35, UN, UNT
  Prozesse: Netznutzungsabrechnung
  Quelle: PRICAT_MIG_2_0d_20240619.pdf
}
UNT_00026 --> UNT_00026_msg_2 : verwendet in
class UNT_00026_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
UNT_00026 ..> UNT_00026_proc_1 : eingebettet in
@enduml