@startuml
title Datenatlas – XXX:G_0081
class XXX_G_0081 {
  Name: Codeliste Gas Nr. G_0081 Codeliste zur Prüfung der Netznutzungsrechnung zwischen NB und LF (Gas)
  Prozesse:
    - Netznutzungsabrechnung
}
class XXX_G_0081_msg_1 {
  Nachricht: REMADV 2.9c
  Kontext: Beispiel:
  Pflichtfeld: Ja
  Codes: EBD, ESA, LF, MGV, MSB, NB, NN, OCR
  Prozesse: Netznutzungsabrechnung
  Quelle: REMADV_MIG_2.9c_außerordentliche_20240726.pdf
}
XXX_G_0081 --> XXX_G_0081_msg_1 : verwendet in
class XXX_G_0081_proc_1 <<process>> {
  Netznutzungsabrechnung
  Gesetze: StromNEV, StromNZV
  Zusammenfassung: Wie funktioniert die Netznutzungsabrechnung zwischen Netzbetreiber und Lieferant?
}
XXX_G_0081 ..> XXX_G_0081_proc_1 : eingebettet in
@enduml